# Dataset
data: aes_128_n3
data_path: 'data'

# Cipher
cipher: Aes
n: 10**7
nr: 3
key_mode: 'random_fixed'
key: null
diff: [0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
# batch_size: 10000
# seed: 42
train_ratio: 0.9
negative_samples: 'real_encryption'
