# Dataset
data: chacha_n3
data_path: 'data'

# Cipher
cipher: Chacha
n: 10**7
nr: 3
key_mode: 'random_fixed'
key: null
diff: [0x00000000, 0x00000000, 0x00000000, 0x00008000]
# batch_size: 10000
# seed: 42
train_ratio: 0.9
negative_samples: 'real_encryption'
