# Dataset
data: speck_32_64_n5
data_path: 'data'

# Cipher
cipher: Speck_32_64
n: 10**7
nr: 5
key_mode: 'input_fixed'
key: [0x1918, 0x1110, 0x0908, 0x0100]
diff: [0x0040, 0]
seed: 42
train_ratio: 0.9
