# Dataset
data: tea_n5
data_path: 'data'

# Cipher
cipher: Tea
n: 10**7
nr: 5
key_mode: 'random_fixed'
key: null
diff: [0x40000000, 0x00000000]
# batch_size: 10000
# seed: 42
train_ratio: 0.9
negative_samples: 'real_encryption'
